[package]
name = "pi_server"
version = "0.5.0"
authors = ["Prashant Bhushan Singh <prashant.bhushansingh@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
once_cell = "1"

log = "0"
log4rs = { version = "1", features = ["file_appender", "rolling_file_appender", "size_trigger"] }

serde = "1"
serde_json = "1"
serde_yaml = "0"

futures-util = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "fs"] }

reqwest = { version = "0", features=["cookies"] }

trust-dns-proto = "0"
trust-dns-client = "0"
trust-dns-server = "0"

# sqlx = { version = "0", features = ["sqlite", "runtime-tokio-native-tls"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
jemallocator = "0"


[profile.release]
lto = true
codegen-units = 1
